obj-$(CONFIG_TESTCASE_CPU_CALC) += tt-cpucalc_dhrystone.o
obj-$(CONFIG_TESTCASE_CPU_CALC) += tt-cpucalc_coremark.o
obj-$(CONFIG_TESTCASE_CPU_FREQ) += tt-cpufreq.o
obj-$(CONFIG_TESTCASE_CPU_THERMAL) += tt-cputhermal.o
