obj-$(CONFIG_AVI_TEST) += avi.o
obj-$(CONFIG_AVI_TEST) += video_test.o
obj-$(CONFIG_AVI_TEST) += dec_display.o

CFLAGS += -I include/
CFLAGS += -I drivers/rtos-hal/include/hal/
CFLAGS += -I components/common/thirdparty/libjpeg-turbo/source/
CFLAGS += -I components/common/thirdparty/libjpeg-turbo/include/
CFLAGS += -I components/common/aw/AudioSystem/include
CFLAGS += -I components/thirdparty/xvid/include

CFLAGS += -Werror