obj-$(CONFIG_TESTCASE_AUDIO_MIC_CAPTURE) += tt-mic_capture.o
obj-$(CONFIG_TESTCASE_AUDIO_SPEAKER_PLAYBACK) += tt-speaker_playback.o
obj-$(CONFIG_TESTCASE_AUDIO_PLAYBACK_AND_CAPTURE) += tt-playback_and_capture.o
obj-$(CONFIG_TESTCASE_AUDIO_PLAYBACK_OPEN_CLOSE) += tt-playback_open_close.o
obj-$(CONFIG_TESTCASE_AUDIO_PLAYBACK_LOOP) += tt-playbackloop.o
obj-$(CONFIG_TESTCASE_AUDIO_CAPTURE_LOOP) += tt-captureloop.o

CFLAGS +=  -I drivers/rtos-hal/hal/source/sound/component/aw-alsa-utils
CFLAGS +=  -I components/common/aw/AudioSystem/include
